### ISSUE TITLE
Add similar commands for NVMe

### ISSUE THREAD

**Issue by fvaninet** [Cisco-SAN/ShowAnalytics#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Expected Output**
A clear and properly formatted output which your are expecting

**Expected Changes in --help output to get the scope**
 A clear and properly formatted expect output for --help option to depict the scope

**Calculations**
 A clear and concise description of the mathematical calculation involved to get the new output

**Additional context**

**Comment by HiteshBatraCisco** [comment]
Resolved
